version: "3"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    java-service:
        build:
            context: ./java
            dockerfile: ./Dockerfile
        container_name: java
        restart: always
        environment:
        - dongtai_name=java-kafka
        volumes:
        - "./dongtai-agent.jar:/opt/agent.jar"
        depends_on:
        - kafka
        ports:
        - '8810:8080'

    go-service:
        build:
            context: ./golang
            dockerfile: ./Dockerfile
        container_name: golang
        restart: always
        entrypoint: ["./producer"]
        volumes:
        - "./dongtai-go-agent-config.yaml:/dongtai/dongtai-go-agent-config.yaml"
        depends_on:
        - kafka
        - java-service
        ports:
        - '8811:8811'
        environment:
        - KAFKA_BROKER=kafka:9092
